### ISSUE TITLE
NullPointerException when user not defined in TAC

### ISSUE THREAD

**Issue by JeanLucPons** [tango-controls/JTango#46] opened 2017-10-10 08:02 UTC
A null pointer exception is thrown when a user is not defined in the TAC.

sys/database/2.DbPutDeviceProperty  -> TangoApi_READ_ONLY_MODE
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at fr.esrf.TangoApi.ConnectionDAODefaultImpl.get_host_name(ConnectionDAODefaultImpl.java:428)
	at fr.esrf.TangoApi.ConnectionDAODefaultImpl.throwNotAuthorizedException(ConnectionDAODefaultImpl.java:831)
	at fr.esrf.TangoApi.ConnectionDAODefaultImpl.command_inout(ConnectionDAODefaultImpl.java:880)
	at fr.esrf.TangoApi.ConnectionDAODefaultImpl.command_inout(ConnectionDAODefaultImpl.java:872)
	at fr.esrf.TangoApi.DatabaseDAODefaultImpl.put_device_property(DatabaseDAODefaultImpl.java:1239)
	at fr.esrf.TangoApi.Database.put_device_property(Database.java:944)

**Comment by Pascal-Verdier** [comment] 2017-10-11 08:54
The problem is linked to the remove of **ApiUtil** class.
The NPE is unexpected but in **throwNotAuthorizedException** method, the parameter **this.get_host_name((Connection)null)** always produce a NPE .

**Comment by Ingvord** [comment] 2017-10-11 09:59
I will have a look into it

@Pascal-Verdier thanks for the investigation

**Comment by Pascal-Verdier** [comment] 2020-09-28 06:26
Fixed by returning to previous release

**Closed as completed by Pascal-Verdier** 2020-09-28 06:26 UTC
